#! /usr/bin/perl -w


BEGIN {
    unless ($ENV{DOCTOOL}) {
        $ENV{DOCTOOL} = "/Users/lehn/Documents/DocToll";

        print STDERR "[INFO] Environment variable DOCTOOL not set.\n";
        print STDERR "[INFO] Using default value \"$ENV{DOCTOOL}\"\n";
    } else {
        print STDERR "[INFO] Using DocTool: \$ENV{DOCTOOL}=\"$ENV{DOCTOOL}\"\n";
    }

    unshift(@INC, "$ENV{DOCTOOL}/Library");
    unshift(@INC, "$ENV{DOCTOOL}/Library/Components");
    unshift(@INC, "$ENV{DOCTOOL}/Library/Tools");
}

use DocUtils;

BEGIN {
    DocUtils->EvalConfigFile(file => "doctool.preconfig");
    DocUtils->EvalConfigFile(file => "$ENV{DOCTOOL}/Configuration/doctool.config");
    DocUtils->EvalConfigFile(file => "doctool.postconfig");
}

use DocEnv;
use SourceFiles;
#use FileTree;

SourceFiles->ProcessFiles();
#SourceFiles->ProcessFile(file => "flens/flens.cxx");
